name: run-tests-and-build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-deps
  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Run tests
        run: |
          npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Build the application
        run: |
          npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-out
          path: ./out
  deploy:
    needs: build
    permissions:
      contents: write
      id-token: write
      pages: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-out
          path: ./out
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out"
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
